import type { SoundItem } from './types'

export const SOUND_CATALOG: SoundItem[] = [
  // --- Nature & Water ---
  {
    id: 'rain-on-window',
    title: 'Rain on Window',
    subtitle: 'Steady glass trickling',
    category: 'nature',
    sourceType: 'audio-file',
    audioUrl: '/sounds/rain-on-window.opus',
    icon: '🌧️',
    description:
      'Calming raindrops against glass, providing comforting rhythm for deep relaxation.',
    license: 'Creative Commons 0 (CC0)',
  },
  {
    id: 'rain-soft-thunder',
    title: 'Rain & Distant Thunder',
    subtitle: 'Soft rumble & gentle storm',
    category: 'nature',
    sourceType: 'audio-file',
    audioUrl: '/sounds/rain-soft-thunder.opus',
    icon: '⛈️',
    description: 'Muffled, soothing rolling thunder and atmospheric rain in the distance.',
    license: 'Creative Commons 0 (CC0)',
  },
  {
    id: 'rain-under-umbrella',
    title: 'Rain Under Umbrella',
    subtitle: 'Close canopy resonance',
    category: 'nature',
    sourceType: 'audio-file',
    audioUrl: '/sounds/rain-under-umbrella.opus',
    icon: '☂️',
    description:
      'Intimate, sheltered feeling of walking safely under a large umbrella in the rain.',
    license: 'Creative Commons 0 (CC0)',
  },
  {
    id: 'rain-on-umbrella-soft',
    title: 'Gentle Canopy Rain',
    subtitle: 'Light rhythmic drops',
    category: 'nature',
    sourceType: 'audio-file',
    audioUrl: '/sounds/rain-on-umbrella-soft.opus',
    icon: '🌂',
    description: 'Delicate, light rain drumming softly against a waterproof awning.',
    license: 'Creative Commons 0 (CC0)',
  },
  {
    id: 'ocean-waves-gentle',
    title: 'Gentle Ocean Waves',
    subtitle: 'Deep rolling surf',
    category: 'nature',
    sourceType: 'audio-file',
    audioUrl: '/sounds/ocean-waves-gentle.opus',
    icon: '🌊',
    description: 'Slow, hypnotic rhythm of sea waves breaking gently upon a sandy shore.',
    license: 'Creative Commons 0 (CC0)',
  },
  {
    id: 'ocean-waves-foam',
    title: 'Ocean Foam & Bubbles',
    subtitle: 'Crisp fizzing surf',
    category: 'nature',
    sourceType: 'audio-file',
    audioUrl: '/sounds/ocean-waves-foam.opus',
    icon: '🏖️',
    description: 'Texture of bubbly seafoam gently washing over pebbles and sand.',
    license: 'Creative Commons 0 (CC0)',
  },
  {
    id: 'ocean-waves-birds',
    title: 'Coastal Surf & Birds',
    subtitle: 'Morning sea breeze',
    category: 'nature',
    sourceType: 'audio-file',
    audioUrl: '/sounds/ocean-waves-birds.opus',
    icon: '🕊️',
    description: 'Peaceful combination of gentle morning tide and subtle distant seabirds.',
    license: 'Creative Commons 0 (CC0)',
  },
  {
    id: 'forest-brook-gentle',
    title: 'Gentle Forest Brook',
    subtitle: 'Crystal babbling water',
    category: 'nature',
    sourceType: 'audio-file',
    audioUrl: '/sounds/forest-brook-gentle.opus',
    icon: '💧',
    description: 'Pristine mountain stream water gently cascading over smooth river stones.',
    license: 'Creative Commons 0 (CC0)',
  },
  {
    id: 'forest-brook-summer',
    title: 'Summer Woodland Stream',
    subtitle: 'Deep murmuring flow',
    category: 'nature',
    sourceType: 'audio-file',
    audioUrl: '/sounds/forest-brook-summer.opus',
    icon: '🌲',
    description: 'Rich, immersive sounds of a woodland creek winding through summer trees.',
    license: 'Creative Commons 0 (CC0)',
  },
  {
    id: 'night-crickets-calm',
    title: 'Distant Night Crickets',
    subtitle: 'Quiet evening serenity',
    category: 'nature',
    sourceType: 'audio-file',
    audioUrl: '/sounds/night-crickets-calm.opus',
    icon: '🌙',
    description: 'Gentle, sleepy nighttime cricket songs echoing in the quiet night air.',
    license: 'Creative Commons 0 (CC0)',
  },
  {
    id: 'night-crickets-buzz',
    title: 'Night Meadow Crickets',
    subtitle: 'Hypnotic meadow buzz',
    category: 'nature',
    sourceType: 'audio-file',
    audioUrl: '/sounds/night-crickets-buzz.opus',
    icon: '🦗',
    description:
      'Steady, rhythmic summer night meadow insects providing constant comforting ambience.',
    license: 'Creative Commons 0 (CC0)',
  },
  {
    id: 'night-countryside-pasture',
    title: 'Night Countryside',
    subtitle: 'Peaceful pastoral evening',
    category: 'nature',
    sourceType: 'audio-file',
    audioUrl: '/sounds/night-countryside-pasture.opus',
    icon: '🌌',
    description:
      'Distant rustic night atmosphere with subtle breeze and quiet countryside calmness.',
    license: 'Creative Commons 0 (CC0)',
  },

  // --- Cozy & Places (Comfort) ---
  {
    id: 'train-cabin-interior',
    title: 'Night Train Cabin',
    subtitle: 'Gentle rolling car sway',
    category: 'comfort',
    sourceType: 'audio-file',
    audioUrl: '/sounds/train-cabin-interior.opus',
    icon: '🚂',
    description: 'Muffled, rhythmic swaying inside a long-distance sleeper train compartment.',
    license: 'Creative Commons 0 (CC0)',
  },
  {
    id: 'train-rail-clatter',
    title: 'Rhythmic Rail Clatter',
    subtitle: 'Hypnotic track cadence',
    category: 'comfort',
    sourceType: 'audio-file',
    audioUrl: '/sounds/train-rail-clatter.opus',
    icon: '🛤️',
    description: 'Soothing, steady click-clack of train wheels gliding over steel tracks.',
    license: 'Creative Commons 0 (CC0)',
  },
  {
    id: 'coffee-shop-ambience',
    title: 'Cozy Coffee Shop',
    subtitle: 'Warm background chatter',
    category: 'comfort',
    sourceType: 'audio-file',
    audioUrl: '/sounds/coffee-shop-ambience.opus',
    icon: '☕',
    description: 'Warm, low-level murmur of a friendly neighborhood cafe, removing lonely silence.',
    license: 'Creative Commons 0 (CC0)',
  },
  {
    id: 'coffee-shop-barista',
    title: 'Quiet Cafe & Barista',
    subtitle: 'Gentle cup clinks & warmth',
    category: 'comfort',
    sourceType: 'audio-file',
    audioUrl: '/sounds/coffee-shop-barista.opus',
    icon: '🥐',
    description: 'Soft ceramic cup sounds and delicate espresso bar ambience in the background.',
    license: 'Creative Commons 0 (CC0)',
  },

  // --- Focus Spectrum (Noise) ---
  {
    id: 'brown-noise',
    title: 'Brown Noise',
    subtitle: 'Deep focus & anxiety relief',
    category: 'noise',
    sourceType: 'procedural-noise',
    noiseType: 'brown',
    icon: '🧘',
    description: 'A deep, heavy rumble that gently masks racing thoughts and inner restlessness.',
    license: 'Procedurally generated via Web Audio API (CC0)',
  },
  {
    id: 'pink-noise',
    title: 'Pink Noise',
    subtitle: 'Balanced gentle spectrum',
    category: 'noise',
    sourceType: 'procedural-noise',
    noiseType: 'pink',
    icon: '🍃',
    description:
      'Deeper than white noise, resembling steady wind through pine trees or distant rainfall.',
    license: 'Procedurally generated via Web Audio API (CC0)',
  },
  {
    id: 'white-noise',
    title: 'White Noise',
    subtitle: 'Static sound mask',
    category: 'noise',
    sourceType: 'procedural-noise',
    noiseType: 'white',
    icon: '📻',
    description: 'Equal energy across audible frequencies, blocking sudden sharp external noises.',
    license: 'Procedurally generated via Web Audio API (CC0)',
  },

  // --- ASMR & Tactile ---
  {
    id: 'book-pages-turning',
    title: 'Book Pages Turning',
    subtitle: 'Slow rhythmic paper ASMR',
    category: 'asmr',
    sourceType: 'audio-file',
    audioUrl: '/sounds/book-pages-turning.opus',
    icon: '📖',
    description: 'Gentle, slow friction of paper pages turning in a quiet sanctuary.',
    license: 'Creative Commons 0 (CC0)',
  },
  {
    id: 'reading-pages-soft',
    title: 'Quiet Reading Room',
    subtitle: 'Delicate library rustles',
    category: 'asmr',
    sourceType: 'audio-file',
    audioUrl: '/sounds/reading-pages-soft.opus',
    icon: '📚',
    description: 'Subtle, relaxing sounds of studying and turning pages in a cozy book nook.',
    license: 'Creative Commons 0 (CC0)',
  },
  {
    id: 'plastic-crinkle-asmr',
    title: 'Soft ASMR Crinkle',
    subtitle: 'Delicate soothing triggers',
    category: 'asmr',
    sourceType: 'audio-file',
    audioUrl: '/sounds/plastic-crinkle-asmr.opus',
    icon: '✨',
    description: 'Ultra-soft, slow micro-crinkles for tingling relaxation and bedtime ASMR calm.',
    license: 'Creative Commons 0 (CC0)',
  },
]
